### ISSUE TITLE
Unused variable definition: var change = old !== value;

### ISSUE THREAD

**Issue by leoj3n** [canjs/can-observe#1]
In this file: https://github.com/canjs/can-observe/blob/9f287a2986db577455c2924b692adcf6b5c93fad/can-observe.js#L22

Did you forget to use `change`? I'm imagining you defined it with the intention of using it like:

``` js
set: function(target, key, value){
  var old = target[key];
  var change = old !== value;
  if (change) {
    target[key] = value;
    can.batch.trigger(target, key, [value, old]);
  }
  return true;
}
```

Or did you add `change` to just illustrate a point?

Thanks!

**Comment by matthewp** [comment]
That makes sense to me, this is likely a bug. Let me see if I can create a breaking example.
