### ISSUE TITLE
Getters aren't properly observable

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-observe#31]
Getters are not called correctly when something they depend on changes. Here is some example code:

```
import observe from 'can-observe';
import stache from 'can-stache';

var data = observe({
    time: new Date(),

    get hh(){
        var hr = this.time.getHours() % 12;
        return hr === 0 ? 12 : hr;
    },

    get mm(){
        return this.time.getMinutes().toString().padStart(2,"00");
    },

    get ss(){
        return this.time.getSeconds().toString().padStart(2,"00");
    }
});

setInterval(() => {
    data.time = new Date();
}, 1000);

var view = stache(`
    {{hh}}:{{mm}}:{{ss}}
`);

document.body.appendChild(
    view(data)
);
```

When the `setInterval` is hit, the getters are not called and the values are set to `data.time` directly:

![observe](https://user-images.githubusercontent.com/5851984/32345592-a8fcafb0-bfd8-11e7-8a0d-740fe66ebbaf.gif)

**Comment by justinbmeyer** [comment]
This is probably a problem with can-view-scope’s fast path

**Comment by phillipskevin** [comment]
Forgot to mention, if these are not getters it works correctly. If you just make them functions and call them in the template like this:
```
{{hh()}}:{{mm()}}:{{ss()}}
```

**Comment by matthewp** [comment]
Getter test is skipped: https://github.com/canjs/can-observe/blob/dfbdc939a1e27dcef87099009aa137545271c4a6/test.js#L309 . I would think that test should be failing.

**Comment by justinbmeyer** [comment]
This should be fixed, if there still is a problem, it's in `can-view-scope`.

getters are still not directly bindable, but they are observable (via Observation) now.

**Comment by justinbmeyer** [comment]
getters are directly observable now.
